Post-it/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using Post_it.Domain.Common;
using Post_it.BootStraper;
using Post_it.Models;

namespace Post_it.Controllers
{
    public class AdminController : Controller
    {
        private IPostItMessageRepository postIt_rep;
        private ISlideRepository slide_rep;

        public AdminController()
	    {
            postIt_rep = PostItMessageRepositoryFactory.Current.GetPostItMessageRepository();
            slide_rep = SlideRepositoryFactory.Current.GetSlideRepository();
	    }

        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        public ActionResult PostItMessage()
        {
            return View(postIt_rep.GetAll().ToList());
        }

        public ActionResult Slides()
        {
            return View(slide_rep.GetAll().ToList());
        }


        public ActionResult CreateSlide()
        {
            return View();
        }

        public ActionResult CreatePostIt()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePostIt(PostItModel model, string returnUrl)
        {
            postIt_rep.Save(new PostItMessage(model.PostItMessage, model.Author));
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSlide(SlideModel model, string returnUrl)
        {
            slide_rep.Save(new Slide(model.slideFilePath));
            return View(model);
        }

        //// GET: /AdminControler/Slides/3

        public ActionResult DeleteSlide(int id)
        {
            Slide slide = slide_rep.GetById(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        public ActionResult DeletePostIt(int id)
        {
            PostItMessage postIt = postIt_rep.GetById(id);
            if (postIt == null)
            {
                return HttpNotFound();
            }
            return View(postIt);
        }

        [HttpPost, ActionName("DeletePostIt")]
        public ActionResult DeleteConfirmedPostIt(int id)
        {
            PostItMessage postIt = postIt_rep.GetById(id);
            if (postIt == null)
            {
                return HttpNotFound();
            }
            else
            {
                postIt_rep.Delete(postIt);
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("DeleteSlide")]
        public ActionResult DeleteConfirmedSlide(int id)
        {
            Slide slide = slide_rep.GetById(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            else
            {
                slide_rep.Delete(slide);
            }
            return RedirectToAction("Index");
        }

    }
}

Post-it/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Post_it.Controllers
{
    public class ClientController : Controller
    {
        //
        // GET: /Client/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendPostit(String message)
        {
            return Json(message, JsonRequestBehavior.DenyGet);
        }

    }
}

Post-it/Controllers/SlideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Post_it.BootStraper;
using Post_it.Domain.Common;

namespace Post_it.Controllers
{
    public class SlideController : Controller
    {
        //
        // GET: /Slide/
        private ISlideRepository slide_rep;
        public ActionResult Index()
        {
            return View();
        }

     

        public ActionResult GetNextSlide(int num, String projectname)
        {
            String result = null;
            slide_rep = SlideRepositoryFactory.Current.GetSlideRepository();
            Slide myprez = slide_rep.GetById(int.Parse(projectname));
            JavaScriptSerializer serialiser = new JavaScriptSerializer();
            Slides np1 = serialiser.Deserialize<Slides>(myprez.JSONData);
            if (num < np1.SlidesList.Count-1)
            {
                result = np1.SlidesList[num+1];
            }
           
            return Json(result, JsonRequestBehavior.DenyGet);
        }

        public ActionResult GetPreviousSlide(int num, String projectname)
        {
            String result = null;
            slide_rep = SlideRepositoryFactory.Current.GetSlideRepository();
            Slide myprez = slide_rep.GetById(int.Parse(projectname));
            JavaScriptSerializer serialiser = new JavaScriptSerializer();
            Slides np1 = serialiser.Deserialize<Slides>(myprez.JSONData);
            if (num > 0)
            {
               result = np1.SlidesList[num-1];
            }

            return Json(result, JsonRequestBehavior.DenyGet);
        }
    }
}

Post-it/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Mon application ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/tiny_mce")
        @Scripts.Render("~/bundles/libXMLScripts")
        @Scripts.Render("~/bundles/libSignalR")
   
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <img src="~/Images/logo.png" alt="" />
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li class="menuButton">@Html.ActionLink("Home", "Index", "Home")</li>
                            @if (User.Identity.Name.Equals("admin")) 
                            { 
                                <li>@Html.ActionLink("Presentator", "Slide", "Home")</li>
                                <li>@Html.ActionLink("SlideEditor","SlideEditor","Home")</li>
                                <li>@Html.ActionLink("Administration","Index","Admin")</li> 
                                
                            }else{
                                <li> @Html.ActionLink("Spectator","Index","Client")</li> 
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>

       
        @RenderSection("scripts", required: false)
    </body>
</html>

Post-it/Views/Shared/_NotAuthorized.cshtml
@{
    ViewBag.Title = "Not Authorized";
}

<h2>@ViewBag.Title</h2>
<p>This access is forbidden for you.</p>